from urllib.request import urlopen
import json
url='https://data.gov.lv/dati/lv/api/3/action/datastore_search?resource_id=d34451d4-3a5a-41b0-9bb7-403201237e69&limit=1000'
with urlopen(url) as response:
    body= response.read()
list = json.loads(body)
for i in list['result']['records']:
    # for k, v in i.items():
        # if k == 'Pārzinis Nosaukums' and v == 'Vides aizsardzības un reģionālās attīstības ministrija':
        # if k == 'Pārzinis Nosaukums' and v == 'Drošības policija':
    print('_id:',i['_id'])
    print('VIS sistēmas numurs:',i['VIS sistēmas numurs'])
    print('Pārzinis Nosaukums:',i['Pārzinis Nosaukums'])
    print('VIS Nosaukums:',i['VIS Nosaukums'])
    print('Vai sistēma satur personu datus:',i['Vai sistēma satur personu datus'])
    print('Vai sistēma satur finanšu datus:',i['Vai sistēma satur finanšu datus'])
    print('Datu apmaiņas protokoli:',i['Datu apmaiņas protokoli'])
    print('Fiziskā aizsardzība:',i['Fiziskā aizsardzība'])
    print('VIS Funkcijas:',i['VIS Funkcijas'])
    print('VIS Lietotāji:',i['VIS Lietotāji'])
    print('Pakalpojumu tarifi:',i['Pakalpojumu tarifi'])
    print('Loģiskā aizsardzība:',i['Loģiskā aizsardzība'])
    print('VIS izveidošanas izmaksas:',i['VIS izveidošanas izmaksas'])
    print('Uzturēšanas izmaksas:',i['Uzturēšanas izmaksas'])
    print('Tiesiskais pamats:',i['Tiesiskais pamats'])
    print('Tehnniskie parametri:',i['Tehnniskie parametri'])
    print('Tīmekļvietne:',i['Tīmekļvietne'])
    print('Kādām sistēmām nodod datus:',i['Kādām sistēmām nodod datus'])
    print('No kādām sistēmām saņem datus:',i['No kādām sistēmām saņem datus'])
    print('Kam sniedz reģ. ISN:',i['Kam sniedz reģ. ISN'])
    print('Kam sniedz reģ. nosauk:',i['Kam sniedz reģ. nosauk'])
    print('No kā saņem reģ. ISN:',i['No kā saņem reģ. ISN'])
    print('No kā saņem reģ. Nosauk:',i['No kā saņem reģ. Nosauk'])
    print('Atbildīgās personas reģistrācijas numurs:',i['Atbildīgās personas reģistrācijas numurs'])
    print('Atbildīgās personas vārds, uzvārds:', i['Atbildīgās personas vārds'], i['Atbildīgās perosnas uzvārds'])
    print('Atbildīgās perosnas tālrunis:', i['Atbildīgās perosnas tālrunis'])
    print('Amatpers.e-pasts:',i['Amatpers.e-pasts'])
    print('Atbildīgās personas darba vieta:',i['Atbildīgās personas darba vieta'])
    print('Darba vietas adrese:',i['Darba vietas adrese'])
    print('Pārzinis Iestādes kods:',i['Pārzinis Iestādes kods'])
    print('Pārzinis Adrese:',i['Pārzinis Adrese'])
    print('Pārzinis Augstākā iestāde:',i['Pārzinis Augstākā iestāde'])
    print('Turētājs Iestādes kods:',i['Turētājs Iestādes kods'])
    print('Turētājs Nosaukums:',i['Turētājs Nosaukums'])
    print('Turētājs Adrese:',i['Turētājs Adrese'])
    print('Turētājs Augstākā iestāde:',i['Turētājs Augstākā iestāde'])
    print('Aktrīvā vai slēgtā sistēma:',i['Aktrīvā vai slēgtā sistēma'])
    print('Slēgšanas datums:',i['Slēgšanas datums'])
    print("--------------------------------------")